openapi: 3.0.0
info:
  title: API сервер для проекта "Шесть городов"
  version: 1.0.0

tags:
  - name: offers
    description: Действия с объявлениями
  - name: auth
    description: Действия с авторизацией
  - name: comments
    description: Действия с комментариями
  - name: favorites
    description: Действия с избранными объявлениями
  - name: premium
    description: Действия с премиум объявлениями
  - name: user
    description: Действия с пользователями

paths:
  /offers:
    get:
      tags:
        - offers
      responses:
        '200':
          description: Список объявлений
          content:
            application/json:
              schema:
                type: array
                maxLength: 60
                items:
                  $ref: '#/components/schemas/offer'
      deprecated: false
    post:
      tags:
        - offers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newOffer'
      responses:
        '200':
          description: Объявление
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      deprecated: false
  /offers/{offerId}:
    get:
      tags:
        - offers
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор объявления
      responses:
        '200':
          description: Объявление
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
      deprecated: false
    patch:
      tags:
        - offers
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор объявления
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newOffer'
      responses:
        '200':
          description: Объявление
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      deprecated: false
    delete:
      tags:
        - offers
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор объявления
      responses:
        '200':
          description: Объявление удалено
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      deprecated: false
  /offers/{offerId}/comments:
    get:
      tags:
        - offers
        - comments
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор объявления
      responses:
        '200':
          description: Список комментариев
          content:
            application/json:
              schema:
                type: array
                maxLength: 50
                items:
                  $ref: '#/components/schemas/comment'
      deprecated: false
    post:
      tags:
        - offers
        - comments
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор объявления
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newComment'
      responses:
        '200':
          description: Комментарий
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      deprecated: false
  /favorites:
    get:
      tags:
        - favorites
        - offers
      responses:
        '200':
          description: Список избранных объявлений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'
      deprecated: false
  /favorites/{offerId}:
    post:
      tags:
        - favorites
        - offers
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор объявления
      responses:
        '200':
          description: Объявление добавлено в избранное
      deprecated: false
    delete:
      tags:
        - favorites
        - offers
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор объявления
      responses:
        '200':
          description: Объявление удалено из избранного
      deprecated: false
  /premium:
    get:
      tags:
        - premium
        - offers
      parameters:
        - name: cityName
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/cityName'
          description: Название города
      responses:
        '200':
          description: Список премиум объявлений
          content:
            application/json:
              schema:
                type: array
                maxLength: 3
                items:
                  $ref: '#/components/schemas/offer'
      deprecated: false
  /login:
    get:
      tags:
        - auth
      responses:
        '200':
          description: Получение данных пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/login'
      deprecated: false
    post:
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
      responses:
        '200':
          description: Данные пользователя
          headers:
            Authorization:
              schema:
                type: string
                description: Токен авторизации
      deprecated: false
  /logout:
    get:
      tags:
        - auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Выход из аккаунта
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      deprecated: false
  /register:
    post:
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/register'
      responses:
        '200':
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      deprecated: false
  /avatar:
    post:
      tags:
        - user
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
      responses:
        '200':
          description: Аватар загружен
      deprecated: false

components:
  responses:
    UnauthorizedError:
      description: Ошибка авторизации
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    location:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number

    cityName:
      type: string
      enum:
        - Paris
        - Cologne
        - Brussels
        - Amsterdam
        - Hamburg
        - Dusseldorf

    city:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/cityName'
        location:
          $ref: '#/components/schemas/location'

    userType:
      type: string
      enum:
        - pro
        - regular

    user:
      type: object
      properties:
        name:
          type: string
        avatarUrl:
          type: string
        type:
          $ref: '#/components/schemas/userType'
        email:
          type: string

    offerType:
      type: string
      enum:
        - apartment
        - room
        - house
        - hotel

    offer:
      type: object
      properties:
        id:
          type: string
          description: Идентификатор объявления
        price:
          type: integer
          description: Цена
        rating:
          type: integer
        title:
          type: string
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        city:
          $ref: '#/components/schemas/city'
        location:
          $ref: '#/components/schemas/location'
        previewImage:
          type: string
        type: 
          $ref: '#/components/schemas/offerType'
        bedrooms:
          type: integer
        description:
          type: string
        goods:
          type: array
          items:
            type: string
        host:
          $ref: '#/components/schemas/user'
        images:
          type: array
          items:
            type: string
        maxAdults:
          type: integer
    newOffer:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        city:
          $ref: '#/components/schemas/city'
        previewImage:
          type: string
        isPremium:
          type: boolean
        type:
          $ref: '#/components/schemas/offerType'
        bedrooms:
          type: integer
        maxAdults:
          type: integer
        price:
          type: integer
        goods:
          type: array
          items:
            type: string
        location:
          $ref: '#/components/schemas/location'
        images:
          type: array
          items:
            type: string

    comment:
      type: object
      properties:
        id:
          type: string
          description: Идентификатор комментария
        user:
          $ref: '#/components/schemas/user'
        rating:
          type: integer
        comment:
          type: string
        date:
          type: string
    newComment:
      type: object
      properties:
        rating:
          type: integer
        comment:
          type: string
    login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    register:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
        type:
          $ref: '#/components/schemas/userType'